// Code generated by MockGen. DO NOT EDIT.
// Source: /home/tim/git/pmgo/database.go

// Package pmgomock is a generated GoMock package.
package pmgomock

import (
	x "."
	gomock "github.com/golang/mock/gomock"
	. "github.com/percona/pmgo"
	reflect "reflect"
)

// MockDatabaseManager is a mock of DatabaseManager interface
type MockDatabaseManager struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseManagerMockRecorder
}

// MockDatabaseManagerMockRecorder is the mock recorder for MockDatabaseManager
type MockDatabaseManagerMockRecorder struct {
	mock *MockDatabaseManager
}

// NewMockDatabaseManager creates a new mock instance
func NewMockDatabaseManager(ctrl *gomock.Controller) *MockDatabaseManager {
	mock := &MockDatabaseManager{ctrl: ctrl}
	mock.recorder = &MockDatabaseManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatabaseManager) EXPECT() *MockDatabaseManagerMockRecorder {
	return m.recorder
}

// C mocks base method
func (m *MockDatabaseManager) C(name string) x.CollectionManager {
	ret := m.ctrl.Call(m, "C", name)
	ret0, _ := ret[0].(x.CollectionManager)
	return ret0
}

// C indicates an expected call of C
func (mr *MockDatabaseManagerMockRecorder) C(name interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "C", reflect.TypeOf((*MockDatabaseManager)(nil).C), name)
}

// CollectionNames mocks base method
func (m *MockDatabaseManager) CollectionNames() ([]string, error) {
	ret := m.ctrl.Call(m, "CollectionNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionNames indicates an expected call of CollectionNames
func (mr *MockDatabaseManagerMockRecorder) CollectionNames() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionNames", reflect.TypeOf((*MockDatabaseManager)(nil).CollectionNames))
}

// DropDatabase mocks base method
func (m *MockDatabaseManager) DropDatabase() error {
	ret := m.ctrl.Call(m, "DropDatabase")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropDatabase indicates an expected call of DropDatabase
func (mr *MockDatabaseManagerMockRecorder) DropDatabase() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropDatabase", reflect.TypeOf((*MockDatabaseManager)(nil).DropDatabase))
}

// Login mocks base method
func (m *MockDatabaseManager) Login(user, pass string) error {
	ret := m.ctrl.Call(m, "Login", user, pass)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login
func (mr *MockDatabaseManagerMockRecorder) Login(user, pass interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockDatabaseManager)(nil).Login), user, pass)
}

// RemoveUser mocks base method
func (m *MockDatabaseManager) RemoveUser(user string) error {
	ret := m.ctrl.Call(m, "RemoveUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUser indicates an expected call of RemoveUser
func (mr *MockDatabaseManagerMockRecorder) RemoveUser(user interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockDatabaseManager)(nil).RemoveUser), user)
}

// Run mocks base method
func (m *MockDatabaseManager) Run(cmd, result interface{}) error {
	ret := m.ctrl.Call(m, "Run", cmd, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockDatabaseManagerMockRecorder) Run(cmd, result interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDatabaseManager)(nil).Run), cmd, result)
}

// UpsertUser mocks base method
func (m *MockDatabaseManager) UpsertUser(user *x.User) error {
	ret := m.ctrl.Call(m, "UpsertUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUser indicates an expected call of UpsertUser
func (mr *MockDatabaseManagerMockRecorder) UpsertUser(user interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockDatabaseManager)(nil).UpsertUser), user)
}
