// Code generated by MockGen. DO NOT EDIT.
// Source: /home/tim/git/pmgo/pmgo.go

// Package pmgomock is a generated GoMock package.
package pmgomock

import (
	x "."
	gomock "github.com/golang/mock/gomock"
	. "github.com/percona/pmgo"
	reflect "reflect"
	time "time"
)

// MockDialer is a mock of Dialer interface
type MockDialer struct {
	ctrl     *gomock.Controller
	recorder *MockDialerMockRecorder
}

// MockDialerMockRecorder is the mock recorder for MockDialer
type MockDialerMockRecorder struct {
	mock *MockDialer
}

// NewMockDialer creates a new mock instance
func NewMockDialer(ctrl *gomock.Controller) *MockDialer {
	mock := &MockDialer{ctrl: ctrl}
	mock.recorder = &MockDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDialer) EXPECT() *MockDialerMockRecorder {
	return m.recorder
}

// Dial mocks base method
func (m *MockDialer) Dial(arg0 string) (x.SessionManager, error) {
	ret := m.ctrl.Call(m, "Dial", arg0)
	ret0, _ := ret[0].(x.SessionManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial
func (mr *MockDialerMockRecorder) Dial(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockDialer)(nil).Dial), arg0)
}

// DialWithInfo mocks base method
func (m *MockDialer) DialWithInfo(arg0 *x.DialInfo) (x.SessionManager, error) {
	ret := m.ctrl.Call(m, "DialWithInfo", arg0)
	ret0, _ := ret[0].(x.SessionManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialWithInfo indicates an expected call of DialWithInfo
func (mr *MockDialerMockRecorder) DialWithInfo(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialWithInfo", reflect.TypeOf((*MockDialer)(nil).DialWithInfo), arg0)
}

// DialWithTimeout mocks base method
func (m *MockDialer) DialWithTimeout(arg0 string, arg1 time.Duration) (x.SessionManager, error) {
	ret := m.ctrl.Call(m, "DialWithTimeout", arg0, arg1)
	ret0, _ := ret[0].(x.SessionManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialWithTimeout indicates an expected call of DialWithTimeout
func (mr *MockDialerMockRecorder) DialWithTimeout(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialWithTimeout", reflect.TypeOf((*MockDialer)(nil).DialWithTimeout), arg0, arg1)
}
